# Generated by Django 4.2 on 2024-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='cardtags',
            options={'verbose_name': 'Связь карточка-тег', 'verbose_name_plural': 'Связи карточка-тег'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='card',
            name='check_status',
            field=models.BooleanField(choices=[(False, 'Не проверено'), (True, 'Проверено')], db_column='CheckStatus', default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_column='UploadDate', verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='cardtags',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
